### ISSUE TITLE
Setup repository folder structure

### ISSUE THREAD

**Issue by MaddaFox** [MaddaFox/Burrow#1]

**Comment by DavidErvin-FS-1** [comment]
[https://github.com/MaddaFox/Burrow/tree/v0.0.1](https://github.com/MaddaFox/Burrow/tree/v0.0.1)

**Comment by MaddaFox** [comment]
Completed:
[https://github.com/MaddaFox/Burrow/tree/v0.0.1](https://github.com/MaddaFox/Burrow/tree/v0.0.1)

Release:
https://github.com/MaddaFox/Burrow/releases/tag/v0.0.1
